#!/bin/bash

function show_usage() {
	echo "Usage: locker [-u | --unlock] FILE"
}

function get_image_name() {
	IMAGE=$1
	NAME=$(echo $IMAGE | grep '^[^@]\+' -o)
	echo $NAME
}

function get_image_digest() {
	IMAGE=$1
	DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE | grep '[^@]\+$' -o)
	echo $DIGEST
}

function lock_image() {
	IMAGE=$1
	NAME=$(get_image_name $IMAGE)
	DIGEST=$(get_image_digest $IMAGE)
	echo $NAME@$DIGEST
}

function unlock_image() {
	IMAGE=$1
	NAME=$(get_image_name $IMAGE)
	echo $NAME
}

function process_dockerfile() {
	OPERATION=$1
	FILE=$2
	LOCKFILE=$FILE.lock

	while IFS= read -r LINE; do
		if [[ $LINE =~ ^FROM ]]
		then
			IMAGE=$(echo "$LINE" | sed -r 's/^FROM +([^ ]+).*$/\1/')
			LOCKIMAGE=$($OPERATION $IMAGE)
			echo "$LINE" | sed -r "s|$IMAGE|$LOCKIMAGE|" >>$LOCKFILE
		else
			echo "$LINE" >>$LOCKFILE
		fi
	done <$FILE

	mv $LOCKFILE $FILE

	echo "Updated $FILE"
}

function process_file() {
	OPERATION=$1
	FILE=$2
	FILEPATH=$(readlink -f $FILE)
	FILENAME=$(basename $FILEPATH)

	case $FILENAME in
		"Dockerfile")
			process_dockerfile $OPERATION $FILEPATH
			;;
		*)
			echo "Unknown file: $FILENAME"
			;;
	esac	
}

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
	show_usage
	exit 1
fi

if [ $1 == "--unlock" ] || [ $1 == "-u" ]
then
	OPERATION="unlock_image"
	shift
else
	OPERATION="lock_image"
fi

FILE=$1
process_file $OPERATION $FILE
