#!/bin/bash

function lock_image() {
	IMAGE=$1
	NAME=$(echo $IMAGE | grep '^[^@]\+' -o)
	DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE | grep '[^@]\+$' -o)
	echo $NAME@$DIGEST
}

function unlock_image() {
	IMAGE=$1
	NAME=$(echo $IMAGE | grep '^[^@]\+' -o)
	echo $NAME
}

function update_dockerfile() {
	OPERATION=$1
	FILE=$2
	LOCKFILE=$FILE.lock

	while IFS= read -r LINE; do
		if [[ $LINE =~ ^FROM ]]
		then
			IMAGE=$(echo "$LINE" | sed -r 's/^FROM +([^ ]+).*$/\1/')
			LOCKIMAGE=$($OPERATION $IMAGE)
			echo "$LINE" | sed -r "s|$IMAGE|$LOCKIMAGE|" >>$LOCKFILE
		else
			echo "$LINE" >>$LOCKFILE
		fi
	done <$FILE

	mv $LOCKFILE $FILE
}

if [ $# -lt 1 ] || [ $# -gt 2 ]
then
	echo "Usage: locker [-u | --unlock] FILE"
	exit 1
fi

if [ $1 == "--unlock" ] || [ $1 == "-u" ]
then
	OPTION="unlock_image"
	shift
else
	OPTION="lock_image"
fi

FILE=$1
FILEPATH=$(readlink -f $FILE)
FILENAME=$(basename $FILEPATH)

case $FILENAME in
	"Dockerfile")
		update_dockerfile $OPTION $FILEPATH
		echo "Updated $FILE"
		;;
	*)
		echo "Unknown file: $FILENAME"
		;;
esac
